# -*- coding: utf-8 -*-
from . import ba_knowledge_mixin
from . import ba_mom
from . import ba_customer_survey
from . import document_page
from . import ba_fsd_feature
from . import ba_fitgap
from . import ba_fsd
from . import ba_master_data
from . import ba_handover
from . import ba_handover_line
from . import ba_wbs_checklist
from . import project_task
from . import project_project
from . import calendar_event
from . import res_partner
from . import product_template
from . import res_partner_industry
from . import ba_project_team
